[build]
  command = "npm run build" 
  publish = "dist"  # or '.output/public' for Nuxt 3

[build.environment]
  NODE_VERSION = "16"  

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["three"]
