// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/4/2025, 4:46:53 PM
const configMerger = require("/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-vr-web-2/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-vr-web-2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-vr-web-2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-vr-web-2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-vr-web-2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-vr-web-2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-vr-web-2/plugins/**/*.{js,ts,mjs}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-vr-web-2/composables/**/*.{js,ts,mjs}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-vr-web-2/utils/**/*.{js,ts,mjs}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-vr-web-2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-vr-web-2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-vr-web-2/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["23"] = "/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/repo-vr-web-2/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})()
